### ISSUE TITLE
tapqir init command

### ISSUE THREAD

**Issue by gelles-brandeis** [gelles-brandeis/tapqir#238]
init command outputs:

Tapqir is a Bayesian program for single-molecule data analysis.
---------------------------------------------------------------
- Checkout the documentation: <https://tapqir.readthedocs.io/>
- Get help on our forum: <https://github.com/gelles-brandeis/tapqir/discussions>
- Star us on GitHub: <https://github.com/gelles-brandeis/tapqir>

I suggest deleting the first line "Tapqir is..." and the last line "Star us..."

**Comment by ordabayevy** [comment]
Closed via #240
