### ISSUE TITLE
CUDA installation

### ISSUE THREAD

**Issue by jc-brandeis** [gelles-brandeis/tapqir#343]
The summary of CUDA installation instructions is out of date: I used the following instructions to install CUDA, but I am not sure the best way to keep the instructions up-to-date as Nvidia updates its instructions.

sudo apt-key del 7fa2af80 [probably not necessary for clean instllation]

wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-keyring_1.0-1_all.deb

sudo dpkg -i cuda-keyring_1.0-1_all.deb

sudo apt-get update

sudo apt-get install cuda

**Comment by ordabayevy** [comment]
> I used the following instructions to install CUDA, but I am not sure the best way to keep the instructions up-to-date as Nvidia updates its instructions.

I will update the tutorial this time. If installation instructions will keep changing frequently then it might be better to just refer users to Nvidia webpage for installation instructions.
