### ISSUE TITLE
errors during colab run

### ISSUE THREAD

**Issue by larryfj** [gelles-brandeis/tapqir#374]
I am attempting to run one of my data sets from the colab based Tapqir.  I placed my data in a new directory within my google drive: MyDrive\NusAGsig0ConstSaltOct1.

All my data files are within that directory.  I selected the glimpse sequence folder, targe aoi file, off-target aoi file and driftlist file.  Upon hitting the 'extract aois' button I received a series of error messages that are listed below.  I did not login to our colab account (not yet aware how to do that), as I was just following the operations specified in the Tapqir analysis (Colab) tutorial.  I had specified an analysis using only frames 2:1812, but all else was normal.

Larry

```
extracting AOIs ...
INFO:tapqir:Extracting AOIs ...
Channel #0 (NusAcy5)
INFO:tapqir.imscroll.glimpse_reader:Channel #0 (NusAcy5)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/tapqir/gui.py](https://localhost:8080/) in glimpseCmd(b, layout, out)
    359             no_input=True,
    360             progress_bar=tqdm_notebook,
--> 361             labels=False,
    362         )
    363 

________________________________________
6 frames
________________________________________
[/usr/local/lib/python3.7/dist-packages/matplotlib/backends/backend_agg.py](https://localhost:8080/) in print_png(self, filename_or_obj, metadata, pil_kwargs, *args, **kwargs)
    503             Metadata in the PNG file as key-value pairs of bytes or latin-1
    504             encodable strings.
--> 505             According to the PNG specification, keys must be shorter than 79
    506             chars.
    507 

ImportError: cannot import name '_png' from 'matplotlib' (/usr/local/lib/python3.7/dist-packages/matplotlib/__init__.py)
```

**Comment by ordabayevy** [comment]
This has to do with installed version of matplotlib library. Until I find a better fix for now you can do this: after installing tapqir go to the menu and click `Runtime -> Restart runtime`

**Comment by gelles-brandeis** [comment]
Yerdos, if you haven't already done so, could you please add this to the installation instructions in the docs?  thanks, Jeff
