### ISSUE TITLE
post analysis: same names are used for saving figures (png) and parameters

### ISSUE THREAD

**Issue by jc-brandeis** [gelles-brandeis/tapqir#379]
In Post Analysis (time-to-first-binding or dwell-time), the same file names are used for saving the results from analyzing fits from different models (Cosmos or cosmos-hmm).  So the most recent analysis overwrites the files from the previous analysis.

**Comment by ordabayevy** [comment]
Thanks for noticing  it @jc-brandeis ! It has been fixed in the latest branch and will be released in the next pip version.
