### ISSUE TITLE
ttb parameter in matlab output

### ISSUE THREAD

**Issue by jc-brandeis** [gelles-brandeis/tapqir#401]
The ttb parameter written to matlab output does not look right.  The first 2 time points look correct, but the subsequent time points  are much larger than the expected values.

**Comment by ordabayevy** [comment]
Hi @jc-brandeis . Sorry for the late reply. Does this happen to other datasets? How big is the jump? Can you print out the values that you have?

**Comment by jc-brandeis** [comment]
The ttb problem happens to another dataset as well, whether using cosmos or cosmos+hmm model for fitting.

in matlab, ttb(1:5,:)-ttb(1,1) gives:
           0          832
         1709         2536
   1.4562e+09   1.4562e+09
   2.9123e+09   2.9123e+09
   4.3685e+09   4.3685e+09
The         0          832      are correct and match the glimpse header ttb data.
         1709         2536

**Comment by ordabayevy** [comment]
This has been fixed in the version 1.1.16
