### ISSUE TITLE
Save values of posterior-sampled dwell times

### ISSUE THREAD

**Issue by gelles-brandeis** [gelles-brandeis/tapqir#402]
Hi Yerdos, Can you make the Post Analysis/Dwell-times tab so that it saves the posterior sampled dwell times in a csv (or other format)  file?

**Comment by ordabayevy** [comment]
Hi Jeff. Merged it to the latest branch. It saves intervals information with low/high codes from which dwell times can be inferred. The name of the file is `{model name}_intervals-channel{c}.csv`. Is this what you were asking for?
